"""Added created_at to Activity model

Revision ID: 0f80903708b7
Revises: 94e72c89fb8a
Create Date: 2025-02-06 19:05:03.378762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f80903708b7'
down_revision: Union[str, None] = '94e72c89fb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'created_at')
    # ### end Alembic commands ###
